version: "3.6"

networks:
  mercado-network:
    driver: bridge

services:
  traefik:
    container_name: "traefik"
    image: traefik
    ports:
      - "80:80/tcp" # The HTTP port
      - "443:443/tcp" # The HTTPS port
    labels:
      - "traefik.http.routers.traefik.rule=Host(`monitor.mercado-futuro.com`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=web"
    command:
      - "--api"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mercado-network
    restart: always

  frontend:
    container_name: frontend
    image: docker.pkg.github.com/robertveloso/mercadofuturo/frontend:latest
    env_file:
      - ./.env.production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`www.mercado-futuro.com`)"
      - "traefik.http.routers.frontend.entrypoints=web"
    networks:
      - mercado-network
    restart: always

  backend:
    container_name: backend
    image: docker.pkg.github.com/robertveloso/mercadofuturo/backend:latest
    env_file:
      - ./.env.production
    environment:
      - DB_HOST=mercado-postgres
      - REDIS_HOST=mercado-redis
      - MONGO_URL=mercado-mongo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.mercado-futuro.com`)"
      - "traefik.http.routers.backend.entrypoints=web"
    depends_on:
      - mercado-postgres
      - mercado-mongo
    networks:
      - mercado-network
    command: node server.js
    restart: always

  mercado-queue:
    container_name: mercado-queue
    image: docker.pkg.github.com/robertveloso/mercadofuturo/backend:latest
    env_file:
      - ./.env.production
    environment:
      - DB_HOST=mercado-postgres
      - REDIS_HOST=mercado-redis
      - MONGO_URL=mercado-mongo
    depends_on:
      - mercado-redis
    networks:
      - mercado-network
    command: node queue.js
    restart: always

  mercado-postgres:
    image: postgres
    container_name: mercado-postgres
    env_file: .env.production
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - mercado-network

  mercado-mongo:
    image: bitnami/mongodb:latest
    container_name: mercado-mongo
    env_file: .env.production
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MONGODB_USERNAME=${MONGO_USER}
      - MONGODB_PASSWORD=${MONGO_PASS}
      - MONGODB_DATABASE=${MONGO_DB}
    ports:
      - "${MONGO_PORT}:27017"
    networks:
      - mercado-network

  mercado-redis:
    image: bitnami/redis:latest
    container_name: mercado-redis
    env_file: .env.production
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "${REDIS_PORT}:6379"
    expose:
      - 6379
    networks:
      - mercado-network
