debug = true

logLevel = "DEBUG"

[traefikLog]
filePath = "/logs/traefik.log"

[accessLog]
filePath = "/logs/access.log"

defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.traefik]
    address = ":8080"
    [entryPoints.traefik.auth]
      [entryPoints.traefik.auth.basic]
        users = ["veloso:$apr1$YAEU0ZcM$g1V3bWkoTKdGg1fzCuRdo0"]
  [entryPoints.http]
  address = ":80"
    #[entryPoints.http.redirect]
    #entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

#[api]
#entrypoint="traefik"

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
watch = true
exposedbydefault = false
swarmmode = false

#[acme]
#email = "mail@velosodigital.com"
#storage = "acme/certs.json"
#entryPoint = "https"
#onHostRule = true
#[acme.httpChallenge]
#entryPoint = "http"
