version: '3.6'

networks:
  mercado-network:
    driver: bridge

services:
  mercado-api:
    build: .
    volumes:
      - .:/home/node/api
    env_file: .env
    labels:
      - 'traefik.enable=true' # Enable reverse-proxy for this service
      - 'traefik.backend=api'
      - 'traefik.frontend.rule=Host:api.mercado-futuro.com' # Domain name for the app
      - 'traefik.frontend.priority=1'
      - 'traefik.port=80'
    environment:
      - DB_HOST=mercado-postgres
      - REDIS_HOST=mercado-redis
      - MONGO_URL=mercado-mongo
    depends_on:
      - mercado-postgres
      - mercado-mongo
    networks:
      - mercado-network
    container_name: mercado-api
    command: yarn dev:start
    ports:
      - '3333:3333'

  mercado-queue:
    build: .
    env_file: .env
    environment:
      - DB_HOST=mercado-postgres
      - REDIS_HOST=mercado-redis
      - MONGO_URL=mercado-mongo
    depends_on:
      - mercado-redis
    networks:
      - mercado-network
    container_name: mercado-queue
    command: yarn dev:queue

  mercado-postgres:
    image: postgres
    container_name: mercado-postgres
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    networks:
      - mercado-network

  mercado-mongo:
    image: bitnami/mongodb:latest
    container_name: mercado-mongo
    env_file: .env
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MONGODB_USERNAME=${MONGO_USER}
      - MONGODB_PASSWORD=${MONGO_PASS}
      - MONGODB_DATABASE=${MONGO_DB}
    ports:
      - '${MONGO_PORT}:27017'
    networks:
      - mercado-network

  mercado-redis:
    image: bitnami/redis:latest
    container_name: mercado-redis
    env_file: .env
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '${REDIS_PORT}:6379'
    expose:
      - 6379
    networks:
      - mercado-network

  traefik:
    container_name: 'traefik'
    image: traefik
    command: --api # Enables the web UI
    ports:
      - '80:80/tcp' # The HTTP port
      - '443:443/tcp' # The HTTPS port
      #- "8080:8080/tcp" # The web UI
    labels:
      - 'traefik.enable=true'
      - 'traefik.frontend.rule=Host:monitor.mercado-futuro.com'
      - 'traefik.backend=traefik'
      - 'traefik.frontend.priority=1'
      - 'traefik.port=8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      - ./traefik.toml:/traefik.toml # Traefik configuration file
      #- ./docker/traefik-acme:/acme # Tell Traefik to save SSL certs here
    network_mode: bridge
    restart: always
