version: '3.6'

networks:
  mercado-network:
    driver: bridge

services:
  mercado-api:
    build: .
    volumes:
      - .:/home/node/api
    env_file: .env
    environment:
      - DB_HOST=mercado-postgres
      - REDIS_HOST=mercado-redis
      - MONGO_URL=mercado-mongo
    depends_on:
      - mercado-postgres
      - mercado-mongo
    networks:
      - mercado-network
    container_name: mercado-api
    command: yarn dev:start
    ports:
      - '3333:3333'

  mercado-queue:
    build: .
    env_file: .env
    environment:
      - DB_HOST=mercado-postgres
      - REDIS_HOST=mercado-redis
      - MONGO_URL=mercado-mongo
    depends_on:
      - mercado-redis
    networks:
      - mercado-network
    container_name: mercado-queue
    command: yarn dev:queue

  mercado-postgres:
    image: postgres
    container_name: mercado-postgres
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    networks:
      - mercado-network

  mercado-mongo:
    image: bitnami/mongodb:latest
    container_name: mercado-mongo
    env_file: .env
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MONGODB_USERNAME=${MONGO_USER}
      - MONGODB_PASSWORD=${MONGO_PASS}
      - MONGODB_DATABASE=${MONGO_DB}
    ports:
      - '${MONGO_PORT}:27017'
    networks:
      - mercado-network

  mercado-redis:
    image: bitnami/redis:latest
    container_name: mercado-redis
    env_file: .env
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '${REDIS_PORT}:6379'
    expose:
      - 6379
    networks:
      - mercado-network
